$(document).ready(function(){
  
var highSchools = [
  "Arcadia High School, Oak Hall",
  "Chincoteague High School, Chincoteague",
  "Nandua High School, Onley",
  "Albemarle High School, Charlottesville",
  "The Miller School of Albemarle, Crozet",
  "Monticello High School, Charlottesville",
  "Murray High School, Charlottesville",
  "Western Albemarle High School, Crozet",
  "Renaissance School, Charlottesville",
  "St. Anne's-Belfield School, Charlottesville",
  "Tandem Friends School, Charlottesville",
  "The Covenant School, Charlottesville",
  "Alexandria Friends School, Alexandria",
  "Bishop Ireton High School, Alexandria",
  "Episcopal High School, Alexandria",
  "Lucas Rainbow Spanish Preschool, Alexandria",
  "Alleghany High School, Low Moor",
  "Amelia Academy, Amelia Court House",
  "Amelia County High School, Amelia Court House",
  "Amherst County High School, Amherst",
  "Appomattox County High School, Appomattox",
  "Arlington Career Center, Arlington",
  "Bishop Denis J. O'Connell High School, Arlington",
  "Wakefield High School, Arlington",
  "Washington-Liberty High School, Arlington",
  "Yorktown High School, Arlington",
  "H-B Woodlawn High School, Arlington",
  "Buffalo Gap High School, Swoope",
  "Fishburne Military School, Waynesboro",
  "Fort Defiance High School, Fort Defiance",
  "Ridgeview Christian School, Stuarts Draft",
  "Riverheads High School, Staunton",
  "Stuart Hall School, Staunton",
  "Stuarts Draft High School, Stuarts Draft",
  "Wilson Memorial High School, Fishersville",
  "Bath County High School, Hot Springs",
  "Liberty High School, Bedford",
  "Staunton River High School, Moneta",
  "Bland County High School, Bland",
  "James River High School, Buchanan",
  "Lord Botetourt High School, Daleville",
  "Virginia High School, Bristol",
  "Brunswick High School, Lawrenceville",
  "Brunswick Academy, Lawrenceville",
  "Council High School, Council",
  "Grundy Senior High School, Grundy",
  "Hurley High School, Hurley",
  "Twin Valley High School, Pilgrim Knob",
  "Buckingham County High School, Buckingham",
  "Parry McCluer High School, Buena Vista",
  "E. C. Glass High School, Lynchburg",
  "Heritage High School, Lynchburg",
  "Holy Cross, Lynchburg",
  "Virginia Episcopal School (VES), Lynchburg",
  "Brookville High School, Lynchburg",
  "Rustburg High School, Rustburg",
  "Altavista High School, Altavista",
  "William Campbell High School, Naruna",
  "Carroll County High School, Hillsville",
  "New Life Christian Academy, Hillsville",
  "Charles City County High School, Charles City",
  "Randolph-Henry High School, Charlotte Court House",
  "Charlottesville High School, Charlottesville",
  "Atlantic Shores Christian School, Chesapeake",
  "Deep Creek High School, Chesapeake",
  "Grassfield High School, Chesapeake",
  "Great Bridge High School, Chesapeake",
  "Great Hope Baptist High School, Chesapeake",
  "Greenbrier Christian Academy, Chesapeake",
  "Hickory High School, Chesapeake",
  "Indian River High School, Chesapeake",
  "Oscar F. Smith High School, Chesapeake",
  "StoneBridge School, Chesapeake",
  "Western Branch High School, Chesapeake",
  "Al Madina School of Richmond, Midlothian",
  "Banner Christian School, Richmond",
  "Carver College & Career Academy, Chester",
  "Chesterfield Career & Technical Center, Chesterfield",
  "Clover Hill High School, Midlothian",
  "Cosby High School, Midlothian",
  "James River High School, Midlothian",
  "Joseph Mastin School at Bon Air, Bon Air",
  "Lloyd C. Bird High School, Chesterfield",
  "Manchester High School, Midlothian",
  "Matoaca High School, Matoaca",
  "Meadowbrook High School, Richmond",
  "Midlothian High School, Midlothian",
  "Monacan High School, Richmond",
  "Richmond Christian School, Chesterfield",
  "Thomas Dale High School, Chester",
  "Clarke County High School, Berryville",
  "Colonial Heights High School, Colonial Heights",
  "Covington High School, Covington",
  "Craig County High School, New Castle",
  "Culpeper County High School, Culpeper",
  "Eastern View High School, Culpeper",
  "Cumberland High School, Cumberland",
  "Galileo Magnet High School, Danville",
  "George Washington High School, Danville",
  "Westover Christian Academy, Danville",
  "Fairfax High School, Fairfax",
  "Paul VI Catholic High School, Fairfax",
  "The New School of Northern Virginia, Fairfax",
  "Annandale High School, Annandale",
  "Bryant Alternative High, Alexandria",
  "Centreville High School, Clifton",
  "Chantilly High School, Chantilly",
  "Thomas A. Edison High School, Alexandria",
  "Falls Church High School, Falls Church",
  "Fairfax High School, Fairfax",
  "Hayfield Secondary School, Alexandria",
  "Herndon High School, Herndon",
  "Justice High School, Falls Church",
  "Lake Braddock Secondary School, Burke",
  "Langley High School, McLean",
  "John R. Lewis High School, Springfield",
  "James Madison High School, Vienna",
  "Marshall High School, Falls Church",
  "McLean High School, McLean",
  "Mount Vernon High School, Alexandria",
  "Oakton High School, Vienna",
  "Robinson Secondary School, Fairfax",
  "South County Secondary School, Lorton",
  "South Lakes High School, Reston",
  "West Potomac High School, Alexandria",
  "West Springfield High School, Springfield",
  "Westfield High School, Chantilly",
  "WT Woodson High School, Fairfax",
  "The Dominion School, Springfield",
  "Flint Hill School, Oakton",
  "GW Community School, Springfield",
  "The Madeira School, McLean",
  "Trinity Christian School, Fairfax",
  "Mountain View Alternative School, Centreville",
  "Oak Hill Christian School, Reston",
  "Phillips School-Annandale, Annandale",
  "Potomac School, McLean",
  "Trinity School at Meadow View, Falls Church",
  "The Fairfax Christian School, Vienna",
  "Fauquier High School, Warrenton",
  "Fresta Valley Christian School, Marshall",
  "Highland School, Warrenton",
  "Kettle Run High School, Nokesville",
  "Liberty High School, Bealeton",
  "The Wakefield School, The Plains",
  "Mountain Vista Governor's School, Warrenton",
  "Floyd County High School, Floyd",
  "Fluvanna High School, Palmyra",
  "Fork Union Military Academy, Fork Union",
  "Franklin High School, Franklin",
  "James Wood High School, Winchester",
  "Millbrook High School, Winchester",
  "Sherando High School, Stephens City",
  "Mountain Vista Governor's School, Middletown",
  "Giles High School, Pearisburg",
  "Narrows High School, Narrows",
  "Jefferson Christian Academy, Ripplemead",
  "Paul S. Blandford School at Beaumont, Beaumont",
  "Goochland High School, Goochland",
  "Benedictine High School, Manakin",
  "Saint Gertrude High School, Manakin",
  "Carlbrook School, Halifax",
  "Halifax County Career Center, Halifax",
  "Halifax County High School, South Boston",
  "Bethel High School, Hampton",
  "Bridgeport Academy, Hampton",
  "Hampton Christian High School, Hampton",
  "Hampton High School, Hampton",
  "Kecoughtan High School, Hampton",
  "Phoebus High School, Hampton",
  "Atlee High School, Mechanicsville",
  "Hanover High School, Mechanicsville",
  "Patrick Henry High School, Ashland",
  "Mechanicsville High School, Mechanicsville",
  "Collegiate School, Richmond",
  "Deep Run High School, Glen Allen",
  "Douglas S. Freeman High School, Richmond",
  "Mills E. Godwin High School, Richmond",
  "Glen Allen High School, Glen Allen",
  "Henrico High School, Richmond",
  "Hermitage High School, Richmond",
  "Hermitage Technical Center, Richmond",
  "Highland Springs High School, Highland Springs",
  "Highland Springs Technical Center, Highland Springs",
  "Landmark Christian School, Richmond",
  "Northstar Academy, Richmond",
  "Virginia Randolph Community High School, Glen Allen",
  "The Steward School, Richmond",
  "J.R. Tucker High School, Richmond",
  "Varina High School, Richmond",
  "Smithfield High School, Smithfield",
  "Windsor High School, Windsor",
  "Isle of Wight Academy, Isle of Wight",
  "Jamestown High School, Williamsburg",
  "Lafayette High School, Williamsburg",
  "Briar Woods High School, Ashburn",
  "Broad Run High School, Ashburn",
  "Dominion High School, Sterling",
  "Freedom High School, South Riding",
  "Heritage High School, Leesburg",
  "Independence High School, Ashburn",
  "John Champe High School, Aldie",
  "Lightridge High School, Aldie",
  "Loudoun County High School, Leesburg",
  "Loudoun Valley High School, Purcellville",
  "Park View High School, Sterling",
  "Potomac Falls High School, Sterling",
  "Riverside High School, Leesburg",
  "Stone Bridge High School, Ashburn",
  "Tuscarora High School, Leesburg",
  "Rock Ridge High School, Ashburn",
  "Woodgrove High School, Purcellville",
  "Foxcroft School, Middleburg",
  "Ideal Schools High School, Ashburn",
  "E. C. Glass High School, Lynchburg",
  "Heritage High School, Lynchburg",
  "Liberty Christian Academy, Lynchburg",
  "Auburn High School, Riner",
  "Blacksburg High School, Blacksburg",
  "Christiansburg High School, Christiansburg",
  "Eastern Montgomery High School, Elliston",
  "Denbigh High School, Newport News",
  "Heritage High School, Newport News",
  "Menchville High School, Newport News",
  "Warwick High School, Newport News",
  "Woodside High School, Newport News",
  "Granby High School, Norfolk",
  "Lake Taylor High School, Norfolk",
  "Matthew Fontaine Maury High School, Norfolk",
  "Norfolk Academy, Norfolk",
  "Norfolk Christian High School, Norfolk",
  "Norfolk Collegiate School, Norfolk",
  "Norfolk Preparatory High School, Norfolk",
  "Norview High School, Norfolk",
  "Booker T. Washington High School, Norfolk",
  "The Hague School, Norfolk",
  "Ghent Montessori School, Norfolk",
  "Chatham Hall, Chatham",
  "Chatham High School, Chatham",
  "Dan River High School, Ringgold",
  "Gretna High School, Gretna",
  "Hargrave Military Academy, Chatham",
  "Tunstall High School, Dry Fork",
  "Alliance Christian High School, Portsmouth",
  "Churchland High School, Portsmouth",
  "I.C. Norcom High School, Portsmouth",
  "Manor High School, Portsmouth",
  "Portsmouth Christian School, Portsmouth",
  "Battlefield High School, near Haymarket",
  "Brentsville District High School, Nokesville",
  "Charles J. Colgan Sr. High School, Manassas",
  "Forest Park High School, Woodbridge",
  "Freedom High School, Woodbridge",
  "Gar-Field Senior High School, Dale City",
  "C. D. Hylton High School, Woodbridge",
  "Osbourn Park High School, Manassas",
  "Patriot High School, Nokesville",
  "Potomac High School, Dumfries",
  "Unity Reed High School, Manassas",
  "Woodbridge High School, Woodbridge",
  "Armstrong High School, Richmond",
  "Franklin Military School, Richmond",
  "Huguenot High School, Richmond",
  "Northstar Academy, Richmond",
  "Thomas Jefferson High School, Richmond",
  "John Marshall High School, Richmond",
  "Maggie L. Walker Governor's School for Government and International Studies, Richmond",
  "Richmond Community High School, Richmond",
  "St. Catherine's School, Richmond",
  "St. Christopher's School, Richmond",
  "Trinity Episcopal High School, Richmond",
  "George Wythe High School, Richmond",
  "Blue Ridge Technical Academy, Roanoke",
  "William Fleming High School, Roanoke",
  "Patrick Henry High School, Roanoke",
  "Roanoke Valley Governor's School for Science and Technology, Roanoke",
  "Noel C. Taylor Learning Academy, Roanoke",
  "Roanoke Catholic School, Roanoke",
  "Cave Spring High School, Roanoke",
  "Hidden Valley High School, Roanoke",
  "William Byrd High School, Vinton",
  "Glenvar High School, Salem",
  "Northside High School, Roanoke",
  "Roanoke County Career Center, Vinton",
  "Arnold R. Burton Technology Center, Salem",
  "North Cross School, Roanoke",
  "Roanoke Valley Christian Schools, Roanoke",
  "Turner Ashby High School, Bridgewater",
  "Broadway High School, Broadway",
  "Spotswood High School, Penn Laird",
  "East Rockingham High School, Elkton",
  "Shenandoah Valley Academy, New Market",
  "Central High School, Woodstock",
  "Massanutten Military Academy, Woodstock",
  "Stonewall Jackson High School, Quicksburg",
  "Strasburg High School, Strasburg",
  "Chancellor High School, Spotsylvania",
  "Courtland High School, Spotsylvania",
  "Massaponax High School, Spotsylvania",
  "Riverbend High School, Spotsylvania",
  "Spotsylvania High School, Spotsylvania",
  "Fredericksburg Academy, Spotsylvania",
  "Fredericksburg Christian School, Spotsylvania",
  "Massaponax Christian Academy, Spotsylvania",
  "Faith Baptist School, Spotsylvania",
  "Brooke Point High School, Stafford",
  "Colonial Forge High School, Stafford",
  "Grace Preparatory School, Stafford",
  "Mountain View High School, Stafford",
  "North Stafford High School, Stafford",
  "Stafford Senior High School, Stafford",
  "King's Fork High School, Suffolk",
  "Lakeland High School, Suffolk",
  "Nansemond River High School, Suffolk",
  "Nansemond-Suffolk Academy, Suffolk",
  "Bayside High School, Virginia Beach",
  "Cape Henry Collegiate School, Virginia Beach",
  "Catholic High School, Virginia Beach",
  "Chesapeake Bay Academy, Virginia Beach",
  "Coastal Christian Academy, Virginia Beach",
  "First Colonial High School, Virginia Beach",
  "Frank W. Cox High School, Virginia Beach",
  "Floyd E. Kellam High School, Virginia Beach",
  "Green Run High School, Virginia Beach",
  "Kempsville High School, Virginia Beach",
  "Landstown High School, Virginia Beach",
  "Ocean Lakes High School, Virginia Beach",
  "Princess Anne High School, Virginia Beach",
  "Salem High School, Virginia Beach",
  "Tallwood High School, Virginia Beach",
  "Abingdon High School, Abingdon",
  "John S. Battle High School, Bristol",
  "Patrick Henry High School, Glade Spring",
  "Holston High School, Damascus",
  "Fort Chiswell High School, Max Meadows",
  "Rural Retreat High School, Rural Retreat",
  "George Wythe High School, Wytheville"
]

var crt = ["critical race theory", "racism", "CRT", "race"]

var kids = ["daughter", "son", "child", "kid", "kids", "children"]
var said = [`My ${kids[Math.floor(Math.random()*kids.length)]} said`, `I over heard my ${kids[Math.floor(Math.random()*kids.length)]} saying`, `My ${kids[Math.floor(Math.random()*kids.length)]}'s homework said`, `My ${kids[Math.floor(Math.random()*kids.length)]}'s teacher said`, `I overheard a teacher saying`]

var ithink = ["I think", "I believe", "I have reason to believe", "I suspect", "If I'm not mistaken"]

var complaint = ["black people deserve equal rights", "slavery bad", "the yassification of history", "white people dont poop", "ben shapiro's wife has a DAP", "the water is turning the damn frogs gay"]

var wap_lyrics = [
  "there's some whores in this house", "certified freak, seven days a week", "wet ass pussy, make that pullout game weak", "you fucking with some wet ass pussy", "bring a bucket and a mop for this wet ass pussy", "give me everything you got for this wet ass pussy", "put this pussy right in yo' face, swipe your nose like a credit card", "hop on top, I want a ride, I do a kegel while it's inside", "spit in my mouth, look at my eyes", "this pussy is wet, come take a dive", "tie me up like I'm surprised", "let's role-play, I wear a disguise", "I want you to park that big Mack truck right in this little garage", "Make it cream, make me scream", "Out in public, make a scene", "I don't cook, I don't clean, But let me tell you, I got this ring", "Gobble me, swallow me, drip down the side of me", "Quick, jump out 'fore you let it get inside of me", "I tell him where to put it, never tell him where I'm 'bout to be", "Talk yo' shit, bite your lip", "Ask for a car while you ride that dick", "You ain't never gotta fuck him for a thing", "He already made his mind up 'fore he came", "Now get your boots and your coat for this wet ass pussy", "He bought a phone just for pictures of this wet ass pussy", "Pay my tuition just to kiss me on this wet ass pussy", "Now make it rain if you wanna see some wet ass pussy", "Look, I need a hard hitter, I need a deep stroke", "I need a Henny drink, I need a weed smoker", "Not a garden snake, I need a king cobra", "With a hook in it, hope it lean over", "He got some money, then that's where I'm headed", "Pussy A-1, just like his credit", "He got a beard, well, I'm tryna wet it", "I let him taste it, and now he diabetic", "I don't wanna spit, I wanna gulp", "I wanna gag, I wanna choke", "I want you to touch that lil' dangly thing that swing in the back of my throat", "My head game is fire, punani Dasani", "It's going in dry, and it's coming out soggy", "I ride on that thing like the cops is behind me", "I spit on his mic' and now he tryna sign me, woo", "Your honor, I'm a freak bitch, handcuffs, leashes", "Switch my wig, make him feel like he cheating", "Put him on his knees, give him some' to believe in", "Never lost a fight, but I'm looking for a beating", "In the food chain, I'm the one that eat ya", "If he ate my ass, he's a bottom feeder", "Big D stand for big demeanor", "I could make ya bust before I ever meet ya", "If it don't hang, then he can't bang", "You can't hurt my feelings, but I like pain", "If he fuck me and ask, \"Whose is it?\"", "When I ride the dick, I'ma spell my name, ah", "Yeah, you fucking with some wet ass pussy", "Bring a bucket and a mop for this wet ass pussy", "Give me everything you got for this wet ass pussy", "Now from the top, make it drop, that's some wet ass pussy", "Now get a bucket and a mop, that's some wet ass pussy", "I'm talking WAP, WAP, WAP, that's some wet ass pussy", "Macaroni in a pot, that's some wet ass pussy, huh"]

var roman = [
  "Take your medication, Roman", "Take a short vacation, Roman", "You need to know your station, Roman", "Some alterations on your clothes and your brain", "Take a little break, little break from your silencing", "There's so much you can take, you can take", "I know how bad you need a Roman holiday", "Roman holiday, a Roman holiday", "You done, you tight? You suck at life?", "You don't want a round three? You done suffered twice", "Wo-wo-worship the queen and you might could pass", "Keep it real, these bitches couldn't wipe my ass", "Anyway, stylist, go get Bvlgari", "I am the ultimate Svengali", "You, you bitches can't even spell that", "You, you hoes buggin', repel that", "Let me tell you this, sister", "I am, I am colder than a blister", "'Cause my flow's so sick, and I'm a lunatic", "And this can't be cured with no Elixir", "'Cause y'all know who the fuck, what the fuck I do", "I done put the pressure to every thug I knew", "Quack, quack to a duck and a chicken too", "Put the hyena in a freakin' zoo, phew!", "Witch, twitch, bitch", "Motherfucking right, this is World War 6", "This right here might make a bitch die", "And this right here is gonna make a bitch cry", "And if we being honest, I am such a great guy", "But this what I do when a bitch breaks flock", "I'ma put her in a dungeon under, under", "No, them bitches ain't eating, they dying of hunger", "Motherfucker, I'm me, who the fuck is this hoe?", "And yes, maybe just a touch of tourettes", "Get my wigs, Terrence, go and get my beret, yo!", "Come all ye faithful, Joyful and triumphant, I am Roman Zolanski", "Talking 'bout me, you talking about me?", "I dare a motherfucker to be talking about me", "Them bitches must be smokin' a couple of OZ's", "They want the outline, I give them a goatee", "Goddamn, motherfucker, you talking about me?", "I dare a motherfucker to be talking about me", "Them bitches must be smokin' a couple of OZ's", "A-buh-buh-buh, now give them a goatee, oh!"]

var mg = [
  "Get it from my mammy, Balmain, bustdown", "Tre Trax I think we got one", "It's Trax season, bruh", "Who that? Trell?", "I want Chanel 9 boots", "All these steady jockin'", "'Cause they know I'm the truth", "Material gworl And I get it from my mammy", "Balmain, bustdowns, these hoes can't stand me", "Material gworl Currently working on a Grammy", "Meanwhile, pussy poppin' with ya man in Miami", "Material girl Chanels and pearls", "That's the trick that it takes to keep the girls", "Choppin' bitches down like Edward Scissor Hands (Scissor Hands)", "I don't want no petty money, run them bands (run them bands)", "Private Island living ,chillin' with Toucan Sam", "Fucking billionaire ballers, rap shit got me grand (ah)", "Motorsport do the dash, drop the top in the Lamb'", "Chanel Bags, that'll make me know it (yeah)", "You need a hot girl? Boy, you gon' have to show it", "You wanna taste, baby boy? you gon' have to throw it", "Deposit all accounts, baby, keep the cash flowin'", "Bust down wrist but, but the bustdown keep 'em going", "Hennessy on my lips, take a sip", "I like my laid, don't come here with no chips", "How much is you payin'? (Payin')", "I don't speak broke boy language (nah)", "You can leave with the crew that you came with (came with)", "Me and my bitches ain't playing (gon' on)", "Ice me out, like Elsa", "Fly me out, private jet, no Delta", "You can send your bitch back to the shelter", "You ain't got no money, bitch, I can't help ya", "Look but don't touch (uh-uh)", "You use to free bitches, I cost too much", "I'm married to the money, baby, you can keep yo' tux", "Stop askin' the same questions, \"Is you fuckin' or what?\" (No)", "I like a super size,, money deluxe", "Where my money? Now you stutter, wh-wh-wh-what?", "Let me make it real clear, fuck, pay up", "Broke leave a bad taste, eww, yuck", "Ocean Drive is where I wanna be (facts)", "Neck on freeze thanks to my girl Tiffany (froze)", "Feet on fleek, steppin' through Balenci'", "You would be crazy as fuck to put her against me (ha)", "Fly me to Cali, swipin' all yo' credit cards, this B.A.P.S, I'm Halle", "Gucci, Louis, Prada it don't matter", "Money make me cum, boy, stop with all the chatter", "Rich eight figures, not enough", "Ten figures private show in the back of the Bentley truck", "Spend yo' money and you still can't cuff", "I want materials and serials, boy, you outta luck", "No stash type of bitch, you ain't keepin' your money tucked (gimme that)", "You bought a Givenchy I'm still stingy no, sir, you can't fuck", "(You said you loved me) Tuh, boy, I told you what?", "You a duck ass, stop cluckin' and pay up", "That's the trick that it takes to keep the girls", "Materials and serials, bitch"]

var low = [
  "Shawty had them apple bottom jeans (jeans)", "Boots with the fur (with the fur)", "The whole club was lookin' at her", "She hit the floor (she hit the floor)", "Next thing you know", "Shawty got low, low, low, low, low, low, low, low", "Them baggy sweat pants and the Reeboks with the straps (with the straps)", "She turned around and gave that big booty a slap (hey)", "She hit the floor (she hit the floor)", "Next thing you know", "Shawty got low, low, low, low, low, low, low, low", , "Hey, I ain't never seen nothin' that'll make me go", "This crazy all night, spending my dough", "Had the million dollar vibe and a body to go", "Them birthday cakes, they stole the show", "So sexual", "She was flexible, professional", "Drinkin' X and O", "Hold up wait a minute, do I see what I think I-, whoa", "Did her thing, I seen shawty get low", "Ain't the same when it's up that close", "Make it rain, I'm makin' it snow", "Work the pole, I got the bankroll", "I'ma say that I prefer the no clothes", "I'm into that, I love women exposed", "She threw it back at me, I gave her more", "Cash ain't a problem, I know where it go", , "She had them apple bottom jeans (jeans)", , "Hey, shawty, what I gotta do to get you home?", "My jeans filled with guap and they ready for shones", "Cadillacs, Maybachs for the sexy grown", "Patron on the rocks that'll make your moan", "One stack c'mon, two stacks c'mon, three stacks c'mon", "Now that's three grand", "What you think I'm playin'? Baby-girl, I'm the man", "I invented rubber bands", "That's what I told her, her legs on my shoulders", "I knew it was over", "That Henny and Cola got me like a soldier", "She ready for Rover, I couldn't control her", "So lucky, oh, me, I was just like a clover", "Shawty was hot like a toaster", "Sorry, but I had to fold her", "Like a pornography poster, she showed her", , "Apple bottom jeans (jeans)", , "Whoa, shawty, yeah she was worth the money", "Lil' mama took my cash", "And I ain't want it back", "The way she bent that back", "Got all them paper stacks", "Tattoo above her crack", "I had to handle that", "I was on it, sexy woman", "Let me showin', and make me want it", "Two in the morning, I'm zoned in", "Them Rosay bottles foaming", "She wouldn't stop, made it drop", "Shawty did that pop and lock", "Had to break her off that guap", "Gal was fly just like my Glock"]

var bonfire = [
  "Okay, it's Childish Gambino, homegirl drop it like the NASDAQ", "Move white girls like there's coke up my asscrack", "Move black girls cause, man, fuck it, I'll do either", "I love pussy, I love bitches, dude, I should be runnin' PETA", "In Adidas, with some short shorts, B-O-O all over me", "My green is where it's supposed to be, your green is in my grocery", "This Asian dude, I stole his girl, and now he got that Kogi beef", "My dick is like an accent mark, it's all about the over Es", "Hot like a parked car", "I sound weird like a hard R", "Fly like the logo on my cousin's four forty", "Eatin' Oreos like these white girls that blow me", "Vodka for my ladies, whiskey for a grown man", "Hangin' in the islands, lookin' for Earl like toe jam", "Butcher and I know it, man, kill beef, go ham", "These rappers are afraid of him", "Cause I'm a beast, bitch, Gir, Invader Zim", "Gambino is a call girl, fuck you, pay me", "Brand new whip for these people like slavery", "They told me I was awful man, that shit did not phase me", "Tell me how I suck again, my memory is hazy", "\"You're my favorite rapper, now\" Yeah, dude, I better be", "Or you can fuckin' kiss my ass, Human Centipede", "You wanna see my girl? I ain't that dumb", "You wanna see my girl? Check Maxim", "\"Man, why does every black actor gotta rap some?\"", "I don't know, all I know is I'm the best one", "It's a bonfire, turn the lights out", "I'm burnin' everything you muthafuckas talk about", "It's a bonfire, turn the lights out", "I'm burnin' everything you muthafuckas talk about", "You know these rapper dudes talk shit, start killin'", "Fuck that, got goons like an arch-villain", "I'm from the South, ain't got no accent, don't know why", "So this rap is child's play, I do my name like Princess Di", "Yeah, they say they want the realness, rap about my real life", "Told me I should just quit \"first of all, you talk white!", "Second off, you talk like you haven't given up yet\"", "Rap's stepfather, yeah, you hate me but you will respect", "I put in work, ask Ludwig", "Put my soul on the track like shoes did", "Played this for my cousin, now he can't even think straight", "Black and white music? Now, that's a mixtape", "Shout out to my blerds, they represent the realness", "Shout out to Gambino, girls, my dick is in the building", "I know you hate me cause your little cousin play me", "I like black girls who nerdy, but when they dance they be sayin' \"owww\"", "Sorry for who followed me", "Chillin' with a Filipino, at your local Jollibee", "Yeah, I'm in her ass like sodomy", "So if you see my hand under the table, don't bother me", "I don't talk soft, that's that other guy", "I'm screamin' \"What the fuck is up?\" like I ain't seen the sky", "And shit I'm doin' this year, Insanity", "Made the beat then murdered it, Casey Anthony", "These rappers don't know what to do", "Cause all I did was act me like a Loony Tune", "I'll give you all of me until there's nothing left", "I swear this summer will be summer camp, bitch"]

var heyya = [
  "One, two, three!", "My baby don't mess around", "Because she loves me so", "This I know fo sho!", "But does she really wanna", "But can't stand to see me walk out the door", "Don't try to fight the feeling", "Because the thought alone is killin' me right now", "Thank God for Mom and Dad", "For sticking to together", "Like we don't know how", "Hey ya! Hey ya!", "You think you've got it", "Oh, you think you've got it", "But got it just don't get it when there's nothin' at all", "We get together", "Oh, we get together", "But separate's always better when there's feelings involved", "Know what they say -its", "Nothing lasts forever!", "Then what makes it, then what makes it", "Then what makes love the exception?", "So why, oh, why, oh", "Why, oh, why, oh, why, oh", "Are we still in denial when we know we're not happy here", "Hey ya! (y'all don't want to here me, ya just want to dance) Hey ya!", "Don't want to meet your daddy (oh ohh), just want you in my caddy (oh ohh)", "Hey ya! (oh, oh!) Hey ya! (oh, oh!)", "Don't want to meet your momma, just want to make you cum-a (oh, oh!)", "I'm (oh, oh) I'm (oh, oh) I'm just being honest! (oh, oh)", "I'm just being honest!", "Hey! alright now! alright now, fellas!", "Yea?", "Now, what cooler than being cool?", "Ice cold!", "I can't hear ya! I say what's, what's cooler than being cool?", "Ice cold!", "Alright alright alright alright alright alright alright alright alright alright alright alright alright alright alright alright!", "Okay, now ladies!", "Yea?", "Now we gonna break this thang down for just a few seconds", "Now don't have me break this thang down for nothin'", "I want to see you on your badest behavior!", "Lend me some sugar, I am your neighbor!", "Ah! Here we go now,", "Shake it, shake it, shake it, shake it, shake it", "Shake it, shake it, shake it, shake it", "Shake it like a Polaroid picture! Hey ya!", "Shake it, shake it, shake it, suga!", "Shake it like a Polaroid picture!", "Now all the Beyonce's, and Lucy Liu's, and baby dolls", "Get on tha floor get on tha floor!", "Shake it like a Polaroid picture!", "Oh, you! oh, you!", "Hey ya!(oh, oh) Hey ya!(oh, oh)"]

var choices = [complaint, wap_lyrics, roman, mg, low, bonfire, heyya]

var arrOfChoice = choices[Math.floor(Math.random()*choices.length)]

var school = highSchools[Math.floor(Math.random()*highSchools.length)]

var schoolArr = school.split(", ")

var theMessage = `${ithink[Math.floor(Math.random()*ithink.length)]} ${schoolArr[0]} in ${schoolArr[1]} is teaching ${crt[Math.floor(Math.random()*crt.length)]}. ${said[Math.floor(Math.random()*said.length)]} "${arrOfChoice[Math.floor(Math.random()*arrOfChoice.length)]}".`

var emailLetter = encodeURIComponent(theMessage)
var subjects = [`School teaching ${crt[Math.floor(Math.random()*crt.length)]}`, `${crt[Math.floor(Math.random()*crt.length)]} being taught`, `${kids[Math.floor(Math.random()*kids.length)]} learning ${crt[Math.floor(Math.random()*crt.length)]}`]

var subject = subjects[Math.floor(Math.random()*crt.length)]

var subject = subject.replace(/\w\S*/g, (w) => (w.replace(/^\w/, (c) => c.toUpperCase())));
  
var emailSubject = encodeURIComponent(subject)

var emailLink=`mailto:helpeducation@governor.virginia.gov?subject=${emailSubject}&body=${emailLetter}`
  $('#email').attr("href", emailLink) 
})